#!/usr/bin/python
#-*- encoding: utf-8 -*-
#Written by Raf
import requests,random, re,os,signal;from time import *;from sys import *; from datetime import *;import sys; from time import *
start = strftime("%a, %d %b %Y %I:%M", localtime())
def Space(j):
	i = 0
	while i<=j:
		print " ",
		i+=1
#Global variables:
homedir = os.environ['HOME'];
blue = '\033[38;5;21m';red = '\033[38;5;1m';yellow = '\033[38;5;11m';green = '\033[38;5;46m';darkgrey='\033[90m'
script_home = sys.path[0];vuln_file='%s'%(script_home)
def sigint_handler(signum, frame):
    print('\nInterrupted.\nCheck vuln log @ %s/vulns.txt'%(script_home))
    exit(1)
signal.signal(signal.SIGINT, sigint_handler)
s=''
logo='𝓒 𝓸 𝓭 𝓮 𝓭 𝓫 𝔂 \033[90m𝓡 𝓪 𝓯, \033[38;5;46m𝓓 𝓮 𝓿 𝓮 𝓵 𝓸 𝓹 𝓮 𝓭  𝓫 𝔂  \033[90m𝓣 𝓣 𝓣 '
am='𝕊ℚ𝕃 𝕚𝕟𝕛𝕖𝕔𝕥𝕠𝕣 '
sql_errors = ["error in your SQL syntax", "Query failed", "supplied argument is not a valid MySQL result resource in",
              "You have an error in your SQL syntax",
              "ORDER BY", "mysql_num_rows()", "SQL query failed", "Microsoft JET Database Engine error '80040e14'",
              "Microsoft OLE DB Provider for Oracle",
              "Error:unknown", "Fatal error", "mysql_fetch", "Syntax error", 'mysql_fetch_array()',
              'expects parameter', 'boolean','Invalid string query','mysql_fetch_assoc()','MYSQL QUERY FAIL',
              'MySQL Error','check the manual that corresponds to your MySQL server',
              'Warning: include()','COULD NOT PERFORM QUERY',]

userAgent = [
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4',
    'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (iPad; CPU OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D201 Safari/9537.53',
    'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.76.4 (KHTML, like Gecko) Version/7.0.4 Safari/537.76.4',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/538.46 (KHTML, like Gecko) Version/8.0 Safari/538.46',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10',
    'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4',
    'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (iPad; CPU OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D201 Safari/9537.53',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/537.75.14',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko) Version/7.0.2 Safari/537.74.9',
    'Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0',
    'Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/537.75.14',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 5.1; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0',
    'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) GSA/4.1.0.31802 Mobile/11D257 Safari/9537.53',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:31.0) Gecko/20100101 Firefox/31.0',
    'Mozilla/5.0 (Windows NT 6.1; rv:24.0) Gecko/20100101 Firefox/24.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:30.0) Gecko/20100101 Firefox/30.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Safari/600.1.3',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36']

UA = random.choice(userAgent)

dork_dictionary = [
'********.php?cid=','********s_in_area.php?area_id=',
'***zine/board.php?board=','?action=',
'?cat=','?id=','?page=','?pagerequested=','?pid=',
'about.php?cartID=','aboutchiangmai/details.php?id=','about_us.php?id=',
'abroad/page.php?cid=','accinfo.php?cartId=','acclogin.php?cartID=',
'add-to-cart.php?ID=','add.php?bookid=','addcart.php?','addItem.php',
'addToCart.php?idProduct=','addtomylist.php?ProdId=','add_cart.php?num=',
'adminEditProductFields.php?intProdID=','advSearch_h.php?idCategory=',
'affiliate-agreement.cfm?storeid=','affiliate.php?ID=',
'affiliates.php?id=','aktuelles/meldungen-detail.php?id=',
'aktuelles/veranstaltungen/detail.php?id=','ancillary.php?ID=',
'answer/default.php?pollID=','archive.php?id=',
'archive/get.php?message_id=','art.php?id=','article.php?id=',
'articlecategory.php?id=','articles.php?id=',
'article_preview.php?id=','artist_art.php?id=','auction/item.php?id=',
'authorDetails.php?bookID=','basket.php?id=','bayer/dtnews.php?id=',
'bbs/bbsView.php?id=','bbs/view.php?no=','beitrag_D.php?id=','beitrag_F.php?id=',
'bid/topic.php?TopicID=','blog.php?blog=',
'blog/index.php?idBlog=','blog_detail.php?id=',
'board/board.html?table=','board/kboard.php?board=',
'board/read.php?tid=','board/showthread.php?t=','board/view.php?no=',
'board/view_temp.php?table=','boardView.php?bbs=','board_view.html?id=','board_view.php?s_board_id=',
'book.html?isbn=','Book.php?bookID=','book.php?ID=','book.php?id=',
'book.php?ISBN=','book.php?isbn=','book/bookcover.php?bookid=',
'bookDetails.php?id=','BookDetails.php?ID=',
'bookmark/mybook/bookmark.php?bookPageNo=','bookpage.php?id=',
'books.php?id=','books/book.php?proj_nr=',
'bookview.php?id=','book_detail.php?BookID=',
'book_list.php?bookid=','book_view.php?bookid=',
'bpac/calendar/event.php?id=','brand.php?id=','browse.php?catid=',
'browse/book.php?journalID=','browsepr.php?pr=',
'browse_item_details.php','Browse_Item_Details.php?Store_Id=',
'buy.php?','buy.php?bookid=',
'bycategory.php?id=','calendar/event.php?id=',
'cardinfo.php?card=','cart.php?action=','cart.php?cart_id=',
'cart.php?id=','cart/addToCart.php?cid=','cart/product.php?productid=',
'cartadd.php?id=','cart_additem.php?id=','cart_validate.php?id=',
'cat.php?cat_id=','cat.php?iCat=','cat/?catid=','catalog.php',
'catalog.php?CatalogID=','catalog/main.php?cat_id=',
'catalog/product.php?cat_id=','catalog/product.php?pid=',
'catalog_item.php?ID=','catalog_main.php?catid=','categories.php?cat=',
'category.php','category.php?c=','category.php?catid=',
'category.php?CID=','category.php?cid=','Category.php?cid=','category.php?id=',
'category.php?id_category=','categorydisplay.php?catid=','category_list.php?id=',
'cats.php?cat=','cbmer/congres/page.php?LAN=',
'cei/cedb/projdetail.php?projID=','cemetery.php?id=',
'channel/channel-layout.php?objId=','checkout.php?cartid=',
'checkout.php?UserID=','checkout1.php?cartid=',
'checkout_confirmed.php?order_id=','clan_page.php?cid=',
'classifieds/detail.php?siteid=','classifieds/showproduct.php?product=',
'cloudbank/detail.php?ID=','club.php?cid=',
'colourpointeducational/more_details.php?id=',
'comersus_listCategoriesAndProducts.php?idCategory=',
'comersus_optEmailToFriendForm.php?idProduct=',
'comersus_optReviewReadExec.php?idProduct=',
'comersus_viewItem.php?idProduct=','comments.php?id=',
'comments_form.php?ID=','community/calendar-event-fr.php?id=',
'Computer Science.php?id=','constructies/product.php?id=',
'contact.php?cartId=','content.php?arti_id=',
'content.php?categoryId=','content.php?cID=','content.php?cid=',
'content.php?cont_title=','content.php?id',
'content.php?id=','content.php?ID=','content.php?p=','content.php?PID=',
'content/conference_register.php?ID=','content/detail.php?id=',
'content/index.php?id=','content/pages/index.php?id_cat=',
'content/programme.php?ID=','content/view.php?id=',
'corporate/newsreleases_more.php?id=','county-facts/diary/vcsgen.php?id=',
'cps/rde/xchg/tm/hs.xsl/liens_detail.html?lnkId=','cryolab/content.php?cid=',
'csc/news-details.php?cat=','customer/board.htm?mode=',
'customer/home.php?cat=','customerService.php?****ID1=',
'db/CART/product_details.php?product_id=','de/content.php?page_id=',
'deal_coupon.php?cat_id=','debate-detail.php?id=',
'default.php?catID=','default.php?cPath=','default.php?TID=',
'description.php?bookid=','designcenter/item.php?id=',
'detail.php?id=','detail.php?ID=','detail.php?item_id=',
'detail.php?prodid=','detail.php?prodID=','detail.php?siteid=',
'detailedbook.php?isbn=','details.php?BookID=',
'details.php?id=','details.php?Press_Release_ID=',
'details.php?ProdID=','details.php?prodID=','details.php?prodId=',
'details.php?Product_ID=','details.php?Service_ID=',
'directory/contenu.php?id_cat=','discussions/10/9/?CategoryID=',
'display.php?ID=','displayArticleB.php?id=',
'displayproducts.php','displayrange.php?rangeid=',
'display_item.php?id=','display_page.php?id=','docDetail.aspx?chnum=',
'download.php?id=','downloads.php?id=','downloads/category.php?c=',
'downloads/shambler.php?id=','downloadTrial.php?intProdID=',
'edatabase/home.php?cat=','edition.php?area_id=',
'education/content.php?page=','els_/product/product.php?id=',
'emailproduct.php?itemid=','emailToFriend.php?idProduct=',
'en/main.php?id=','en/news/fullnews.php?newsid=',
'en/publications.php?id=','eng/rgboard/view.php?&bbs_id=',
'english/board/view****.php?code=','english/fonction/print.php?id=',
'english/print.php?id=','english/publicproducts.php?groupid=',
'eng_board/view.php?T****=','event.php?id=','events.php?ID=',
'events/detail.php?ID=','events/event.php?ID=',
'events/event.php?id=','events/event_detail.php?id=',
'events/index.php?id=','events/unique_event.php?ID=',
'events?id=','event_details.php?id=',
'event_info.php?p=','exhibitions/detail.php?id=',
'exhibition_overview.php?id=','e_board/modifyform.html?code=',
'faq.php?cartID=','faqs.php?id=','faq_list.php?id=',
'fatcat/home.php?view=','feature.php?id=',
'features/view.php?id=','feedback.php?title=',
'FernandFaerie/index.php?c=','filemanager.php?delete=',
'forum/profile.php?id=','forum/showProfile.php?id=',
'fr/commande-liste-categorie.php?panier=','freedownload.php?bookid=',
'free_board/board_view.html?page=','front/bin/forumview.phtml?bbcode=',
'frontend/category.php?id_category=','fshstatistic/index.php?PID=',
'fullDisplay.php?item=','FullStory.php?Id=','galerie.php?cid=',
'gallery.php?id=','gallery/detail.php?ID=',
'gallery/gallery.php?id=','gallerysort.php?iid=',
'garden_equipment/Fruit-Cage/product.php?pr=','garden_equipment/pest-weed-control/product.php?pr=',
'gb/comment.php?gb_id=','general.php?id=',
'getbook.php?bookid=','GetItems.php?itemid=','giftDetail.php?id=','gig.php?id=',
'global/product/product.php?gubun=','global_projects.php?cid=',
'gnu/?doc=','goboard/front/board_view.php?code=',
'goods_detail.php?data=','help.php?CartId=',
'help/com_view.html?code=','HistoryStore/pages/item.php?itemID=',
'hm/inside.php?id=','home.php?cat=',
'home.php?ID=','home.php?id=','html/print.php?sid=',
'html/scoutnew.php?prodid=','htmlpage.php?id=',
'i-know/content.php?page=','ibp.php?ISBN=','idlechat/message.php?id=',
'index.php/en/component/pvm/?view=','index.php?action=',
'index.php?area_id=','index.php?book=','index.php?cart=','index.php?cartID=',
'index.php?cat=','index.php?cid=','index.php?cont=',
'index.php?cPath=','index.php?i=','index.php?id=','index.php?ID=',
'index.php?lang=','index.php?modus=','index.php?news=','index.php?offs=',
'index.php?option=','index.php?page=','index.php?pageId=',
'index.php?pageid=','index.php?pagina=','index.php?pg_t=','index.php?pid=',
'index.php?section=','index.php?site=','index.php?t=','index.php?url=',
'index.php?w=','index_en.php?id=','index_en.php?ref=','info.php?ID=',
'Interior/productlist.php?id=','irbeautina/product_detail.php?product_id=',
'item.php?eid=','item.php?id=',
'item.php?iid=','item.php?itemid=','item.php?item_id=','item.php?model=',
'item.php?prodtype=','item.php?shopcd=','item.php?sub_id=',
'item/detail.php?num=','itemDesc.php?CartId=','itemdetail.php?item=',
'itemdetails.php?catalogid=','item_book.php?CAT=',
'item_details.php?catid=','item_list.php?cat_id=',
'item_list.php?maingroup','item_show.php?code_no=',
'item_show.php?id=','item_show.php?lid=','kboard/kboard.php?board=',
'KM/BOARD/readboard.php?id=','knowledge_base/detail.php?id=',
'kshop/product.php?productid=','learnmore.php?cartID=',
'library.php?cat=','links.php?catid=','list.php?bookid=',
'List.php?CatID=','listcategoriesandproducts.php?idCategory=',
'listing.php?cat=','lmsrecords_cd.php?cdid=',
'ls.php?id=','magazin.php?cid=','magazine-details.php?magid=',
'magazines/adult_magazine_full_year.php?magid=','magazines/adult_magazine_single_page.php?magid=',
'main.php?id=','main.php?item=','main.php?prodID=',
'main/index.php?action=','main/index.php?uid=',
'main/magpreview.php?id=','mall/more.php?ProdID=',
'mboard/replies.php?parent_id=','mb_showtopic.php?topic_id=',
'media/pr.php?id=','melbourne_details.php?id=','message/comment_threads.php?postID=',
'modline.php?id=','module/range/dutch_windmill_collection.php?rangeId=',
'modules.php?****=','modules.php?bookid=','modules/content/index.php?id=',
'modules/forum/index.php?topic_id=','more_detail.php?id=',
'more_detail.php?X_EID=','More_Details.php?id=','more_details.php?id=',
'myaccount.php?catid=','m_view.php?ps_db=','naboard/memo.php?bd=',
'news.php?ID=','news.php?id=','news.php?t=','news.php?type=',
'news/detail.php?id=','news/latest_news.php?cat_id=',
'news/news.php?id=','news/news/title_show.php?id=',
'news/newsitem.php?newsID=','news/newsletter.php?id=',
'news/shownewsarticle.php?articleid=','news/temp.php?id=',
'newsite/pdf_show.php?id=','newsitem.php?newsid=',
'newsItem.php?newsId=','newsitem.php?newsID=','news_and_notices.php?news_id=',
'news_content.php?CategoryID=','news_item.php?id=',
'notify/notify_form.php?topic_id=','nyheder.htm?show=',
'n_replyboard.php?typeboard=','obio/detail.php?id=',
'ogloszenia/rss.php?cat=','onlinesales/product.php?product_id=',
'order.asp?lotid=','order.php?BookID=','order.php?id=','order.php?item_ID=',
'OrderForm.php?Cart=','ourblog.php?categoryid=',
'ov_tv.php?item=','packages_display.php?ref=',
'page.php?area_id=','page.php?id=',
'page.php?modul=','page.php?module=','page.php?PartID=','page.php?pId=',
'page/de/produkte/produkte.php?prodID=','page/venue.php?id=',
'pages.php?ID=','pages.php?id=','pages/print.php?id=','pages/video.php?id=',
'Pages/whichArticle.php?id=','past-event.php?id=',
'payment.php?CartID=','pdetail.php?item_id=','pdf_post.php?ID=',
'pharmaxim/category.php?cid=','photogallery.php?id=',
'php/event.php?id=','php/fid8E1BED06B1301BAE3ED64383D5F619E3B1997A70.aspx?s=',
'php/fid985C124FBD9EF3A29BA8F40521F12D097B0E2017.aspx?s=','php/index.php?id=',
'phpx?PageID','picgallery/category.php?cid=',
'podcast/item.php?pid=','poem_list.php?bookID=',
'ponuky/item_show.php?ID=','portafolio/portafolio.php?id=',
'powersearch.php?CartId=','press_release.php?id=','prev_results.php?prodID=',
'price.php','print-story.php?id=','print.php?ID=','print.php?id=',
'print.php?sid=','printcards.php?ID=','privacy.php?cartID=','prod.php?cat=',
'prodbycat.php?intCatalogID=','proddetails_print.php?prodid=',
'prodetails.php?prodid=','prodlist.php?catid=','prodotti.php?id_cat=',
'product-list.php?category_id=','product-list.php?cid=',
'product-list.php?id=','product-range.php?rangeID=','product.php?****=',
'product.php?bid=','product.php?bookID=','product.php?cat=',
'product.php?id=','product.php?id_h=','product.php?intProdID=',
'product.php?intProductID=','product.php?ItemID=',
'product.php?ItemId=','product.php?pid=','product.php?prd=','product.php?prodid=',
'product.php?product=','product.php?ProductID=','product.php?productid=',
'product.php?product_id=','product.php?shopprodid=',
'product.php?sku=','product/detail.php?id=','product/list.php?pid=',
'product/product.php?cate=','product/product.php?product_no=',
'productDetails.php?idProduct=','productDisplay.php',
'productinfo.php?item=','productList.php?cat=',
'productlist.php?fid=','productlist.php?grpid=',
'productlist.php?id=','productList.php?id=','ProductList.php?id=',
'productlist.php?tid=','productlist.php?ViewType=Category&CategoryID=',
'productpage.php','products-display-details.php?prodid=',
'products.php?act=','products.php?cat=','products.php?categoryID=',
'products.php?catid=','products.php?cat_id=','products.php?DepartmentID=',
'products.php?groupid=','products.php?ID=','products.php?keyword=',
'products.php?openparent=','products.php?p=',
'products.php?rub=','products.php?type=',
'products/?catID=','products/Blitzball.htm?id=',
'products/card.php?prodID=','products/index.php?rangeid=',
'products/parts/detail.php?id=','products/product-list.php?id=',
'products/product.php?id=','products/product.php?pid=',
'products/products.php?p=','productsByCategory.php?intCatalogID=',
'productsview.php?proid=','products_category.php?CategoryID=',
'products_detail.php?CategoryID=','product_detail.php?product_id=',
'product_details.php?id=','product_details.php?prodid=',
'product_details.php?product_id=','product_info.php?id=',
'product_info.php?item_id=','product_info.php?products_id=',
'product_ranges_view.php?ID=','prodView.php?idProduct=',
'profile.php?id=','profiles/profile.php?profileid=',
'profile_print.php?id=','projdetails.php?id=','projects/event.php?id=',
'promo.php?id=','promotion.php?catid=','properties.php?id_cat=',
'property.php?id=','psychology/people/detail.php?id=',
'pub/pds/pds_view.php?start=','publications.php?id=',
'publications.php?Id=','publications.php?ID=',
'publications/book_reviews/full_review.php?id=','publications/publication.php?id=',
'publications/view.php?id=','purelydiamond/products/category.php?cat=',
'pview.php?Item=','pylones/item.php?item=','questions.php?questionid=',
'rating.php?id=','rating/stat.php?id=','recipe/category.php?cid=',
'redaktion/whiteteeth/detail.php?nr=','referral/detail.php?siteid=',
'releases_headlines_details.php?id=','remixer.php?id=','reply.php?id=',
'resellers.php?idCategory=','resources/detail.php?id=',
'resources/index.php?cat=','resources/vulnerabilities_list.php?id=',
'results.php?cat=','review/review_form.php?item_id=',
'reviews.php?id=','rounds-detail.php?id=',
'rss.php?cat=','rss/event.php?id=','rtfe.php?siteid=',
's.php?w=','Sales/view_item.php?id=','savecart.php?CartId=',
'schule/termine.php?view=','search.php?CartID=',
'search/display.php?BookID=','searchcat.php?search_id=',
'section.php?section=','Select_Item.php?id=',
'Services.php?ID=','shippinginfo.php?CartId=',
'shop.php?a=','shop.php?action=','shop.php?bookid=','shop.php?cartID=',
'shop/books_detail.php?bookID=','shop/category.php?cat_id=',
'shop/eventshop/product_detail.php?itemid=','Shop/home.php?cat=',
'shop/home.php?cat=','shop/index.php?cPath=',
'shopaddtocart.php','shopaddtocart.php?catalogid=',
'shopbasket.php?bookid=','shopbycategory.php?catid=',
'shopcafe-shop-product.php?bookId=','shopcart.php?title=',
'shopcreatorder.php','shopcurrency.php?cid=',
'shopdc.php?bookid=','shopdisplaycategories.php',
'shopdisplayproduct.php?catalogid=','shopdisplayproducts.php','shopexd.php','shopexd.php?catalogid=',
'shopping_basket.php?cartID=','shopprojectlogin.php',
'shopquery.php?catalogid=','shopremoveitem.php?cartid=',
'shopreviewadd.php?id=','shopreviewlist.php?id=',
'ShopSearch.php?CategoryID=','shoptellafriend.php?id=',
'shopthanks.php','shopwelcome.php?title=','shop_details.php?prodid=',
'shop_display_products.php?cat_id=','show-book.php?id=',
'show.php?id=','showbook.php?bookid=','showfeature.php?id=',
'showproduct.php?cat=','showproduct.php?prodid=','showproduct.php?productId=',
'showStore.php?catID=','showsub.php?id=','show_bug.cgi?id=',
'show_item.php?id=','show_item_details.php?item_id=',
'shprodde.php?SKU=','sinformer/n/imprimer.php?id=',
'singer/detail.php?siteid=','site.php?id=','site/?details&prodid=',
'site/en/list_service.php?cat=','site/products.php?prodid=',
'sitio/item.php?idcd=','skunkworks/content.php?id=',
'socsci/events/full_details.php?id=','socsci/news_items/full_story.php?id=',
'software_categories.php?cat_id=','specials.php?id=',
'specials.php?osCsid=','sport.php?revista=',
'staff/publications.php?sn=','stat.php?id=',
'static.php?id=','stockists_list.php?area_id=',
'store-details.php?id=','store.php?cat_id=','store.php?id=',
'store/default.php?cPath=','store/description.php?iddesc=',
'store/home.php?cat=','store/index.php?cat_id=',
'store/product.php?productid=','store/view_items.php?id=',
'storefront.php?id=','storefronts.php?title=','storeitem.php?item=',
'storemanager/contents/item.php?page_code=',
'StoreRedirect.php?ID=','store_bycat.php?id=','store_listing.php?id=',
'Store_ViewProducts.php?Cat=','story.php?id=','subcategories.php?id=',
'summary.php?PID=','tas/event.php?id=',
'tecdaten/showdetail.php?prodid=','tek9.php?',
'template.php?Action=Item&pid=','templet.php?acticle_id=','things-to-do/detail.php?id=',
'today.php?eventid=','tools/print.php?id=','topic.php?ID=','toynbeestudios/content.php?id=',
'trailer.php?id=','tuangou.php?bookid=',
'type.php?iType=','updatebasket.php?bookid=','updates.php?ID=','usb/devices/showdev.php?id=',
'veranstaltungen/detail.php?id=','video.php?id=',
'view-event.php?id=','view.php?cid=','view.php?id=',
'view.php?pageNum_rscomp=','view/7/9628/1.html?reply=',
'viewapp.php?id=','viewcart.php?CartId=','viewCart.php?userID=',
'viewCat_h.php?idCategory=','viewevent.php?EventID=','viewitem.php?recor=',
'viewPrd.php?idcategory=','ViewProduct.php?misc=',
'viewthread.php?tid=','view_author.php?id=',
'view_cart.php?title=','view_detail.php?ID=',
'view_item.php?id=','view_item.php?item=',
'view_items.php?id=','view_newsletter.php?id=',
'voteList.php?item_ID=','whatsnew.php?idCategory=',
'wiki/pmwiki.php?page****=','WsAncillary.php?ID=','WsPages.php?ID=noticiasDetalle.php?xid=',
'www/index.php?page=','yacht_search/yacht_view.php?pid=',
'YZboard/view.php?id=','zb/view.php?uid=','_news/news.php?id='
]
for l in logo:
	sys.stdout.write('\r')
	sys.stdout.write(blue+'['+green + '*~*'+blue + ']'+red+' %s'%(am.decode('utf8', errors='ignore'))+green+'%s'%(s.decode('utf8', errors='ignore')))#+greeen+'►'+white+'%s'%logo)#+white+'%d%%'% (5*i))
	s+='%s'%l
	sys.stdout.flush()
	sleep(.01)
print 

class get:
	def __init__(self,total_attempts=0,dork_attempts=0,vulns=0):
		self.session=requests.Session()
		Space(9);print darkgrey+' %s' % start
		Space(7);print blue+'Use custom dorks'+green+'('+yellow+'1'+green+')'+blue+' or dictionary'+green+'('+yellow+'2'+green+')'+blue+' ?'
		answer=raw_input(blue + '┣▇▇▇═─'+red+'─ '+green)
		if answer =='1' or answer == 'custom':
			Space(5);print blue+'Enter dorks separated by a space'+green+'('+yellow+'Ex'+blue+'.'+yellow+' index view page login'+green+')'
			aaa = raw_input(blue + '┣▇▇▇═─'+red+'─ '+green).split()
			dorks = [] 
			for i in aaa:
				dorks.append(i)
		elif answer=='2' or answer == 'dictionary':
			dorks = dork_dictionary
		t1 = datetime.now()
		for dork in dorks:
			dork = random.choice(dorks)
			dork_attempts+=1
			string='Searching \033[90m%s '%dork
			s=''
			for l in string:
				sys.stdout.write('\r')
				sys.stdout.write(blue+'['+green + '?'+blue + '] '+green+'%s'%(s.decode('utf8', errors='ignore')))
				s+='%s'%l
				sys.stdout.flush()
				sleep(.02)
			print
			self.session.headers.update({'User-Agent':'User-Agent: '+UA})
			try:
				page=self.session.get('http://www.bing.com/search?q=%s'%dork).text
				links=list(set(re.findall('class="b_algo"><h2><a href="([A-Za-z0-9-//-=.-?:-_\:]+)',page)))
			except:
				dork = random.choice(dorks)
				page=self.session.get('http://www.bing.com/search?q=%s'%dork).text
				links=list(set(re.findall('class="b_algo"><h2><a href="([A-Za-z0-9-//-=.-?:-_\:]+)',page)))
			for link in links:
				if 'Facebook' in link or 'facebook' in link:
					links.pop(links.index(link))
			for link in links:
				if 'http' not in link:
					link = 'http://%s' % link
				try:
					page = self.session.get(link + '%27').text
					total_attempts+=1
				except:
					pass
				dork_attempts+=1
				for sql_error in sql_errors:
					if sql_error in page:
						vulns+=1
						found=strftime("%a, %d %b %Y %I:%M", localtime())
						print blue+'['+green + '%s'%vulns+blue + '] '+green+'Found '+red+'"%s"'%sql_error
						with open('%s/vulns.txt'%vuln_file.replace('\n',''),'a') as out:
							out.write('{}\n{}\n'.format(found,link))
						try:
							for link in links:
								links.pop(links.index(link))
						except:
							for link in links:
								link = link.replace('http://', '')
								links.pop(links.index(link))
						d=''
						lol='%s '%link
						for l in lol:
							sys.stdout.write('\r')
							sys.stdout.write(blue+'['+green + '%s'%vulns+blue + '] '+darkgrey+'%s'%(d.decode('utf8', errors='ignore')))
							d+='%s'%l
							sys.stdout.flush()
							sleep(.02)
						print
			Space(7);print green+'Tried'+blue+' %s'%dork_attempts+green+' links with'+blue+' %s'%dork
			dork_attempts=0
		t2 = datetime.now()
		time = t2 - t1
		Space(7);print green+'Tried'+blue+' %s'%total_attempts+green+' links in: '+blue+'%s'%(time)
		Space(7);print green+'A total of '+blue+'%s '%vulns+green+'vulnerable links'
me=get()



